### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/SussexPhysioProtocol#1]
https://github.com/RealityBending/SussexPhysioProtocol/blob/b9372e2b8472aff6741876a819b65835c7bce6ca/README.md?plain=1#L27

> It is important to note that participants in your study will need to read and sign the form.

@JingxiongXu does that mean that the risk assessment form that we filled up for the ethics will be also signed by all participants alongside the consent form? I don't think so right? 🤔

**Comment by JingxiongXu** [comment]
It was mentioned in the form that: 

"Section 4 Communication of Risk Assessment to Users
This assessment can either be communicated to groups or Individuals as part of a School or Divisional process or signed off by individual users.  

School or Divisional Process
The contents of this risk assessment will be communicated to builder users in the University training programmes.

Sign-off by users
All individuals carrying out activities covered under this risk assessment should sign below after reading it.
By signing this document you confirm that; you have read and understood this risk assessment and that it is an accurate representation of work practice"

I believe this means that participants will have to sign it along with the info&consent form?

**Comment by DominiqueMakowski** [comment]
🤔 I'll ask John

**Comment by DominiqueMakowski** [comment]
> All individuals carrying out activities covered under this risk assessment should sign below after reading it.
By signing this document you confirm that; you have read and understood this risk assessment and that it is an accurate representation of work practice

Nah after re-reading I'm pretty sure that this applies for the researchers that are working under this protocol, as in "the users of that equipment" but doesn't apply to the participants
